# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

source 'https://cdn.cocoapods.org/'

def shared_pods
  pod 'Alamofire'
end

target 'desafio-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios
  shared_pods

  target 'desafio-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-iosUITests' do
    # Pods for testing
  end

end
